name: Trivy Security Scan

on:
  workflow_call:

jobs:
  trivy:
    name: Trivy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1

      - name: Trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          format: table
          exit-code: 1
          version: latest
